### ISSUE TITLE
node 4.0 failed to run !

### ISSUE THREAD

**Issue by Pana** [jackhutu/jackblog-angular2#1]
在我本地环境, node 4.0
npm install 最终会有一个错误:

```
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/Pana/.nvm/versions/node/v4.2.1/bin/node" "/Users/Pana/.nvm/versions/node/v4.2.1/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package angular2@2.0.0-beta.12 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer ng2-bootstrap@1.0.7 wants angular2@2.0.0-beta.9

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Pana/Projects/tmp/jackblog-angular2/npm-debug.log
```

 在 0.12 环境上也报错了.

但是包貌似都是装上了
之后 gulp build 
然后  node server.js 
在浏览器中访问   localhost:8050   页面空白
浏览器中报错  polyfills.bundle.js:6 Uncaught TypeError: Cannot read property 'fork' of undefined

请问要如何才能运行起这个项目呢?

**Comment by hutuxuhui** [comment]
angular2 的有几个依赖是写死的, 由于 ng2-bootstrap依赖于 angular2@2.0.0-beta.9,  所以目前angular2只能安装beta.9, 你可以先卸掉npm uninstall angular2, 然后安装npm i ng2-bootstrap, 它会自动安装angular2.
另外, 安装好后, 你通过gulp serve 启动开发模式, 会自动打开localhost:5300页面. 如果你装了服务端并且启动的话, 就可以看到带数据的页面了.
