### ISSUE TITLE
article.service的getPrenext和getArticleDetail，数据输出两次

### ISSUE THREAD

**Issue by lishoulong** [jackhutu/jackblog-angular2#3]
Hi Jack
我运行这个项目的时候遇到了几个问题，所以向你请教一下。

1.首先是article.service.ts下的getPrenext和getArticleDetail两个方法，当我console.log数据的时候，控制台输出两次数据，我从后台的方法console数据显示一条，后台是正常的，为什么请求到前台后数据就翻倍了，我不清楚时什么原因导致的。
下面是相关代码。
"
        .................article.isLike = isLike
                return article
            })
            .subscribe((article: ArticleDetailModel) => {
                this.ArticleDetailSubject.next(article)
                console.log(article)      //这个位置输入两条以上的article数据。
            }, (err: Response) => {
                this.ArticleDetailSubject.next(this.articleDetailInitialState)
            })
"
2.在tsconfig.json文件中，“awesomeTypescriptLoaderOptions”下的json文件，因为""cacheDirectory": "node_modules/.awesome-typescript-loader-cache1""，导致service文件无法编译成功，当把这个文件删除，并且禁用cache就可以编译成功了。

所以希望能帮我解惑，多谢。

**Comment by hutuxuhui** [comment]
不好意思啊, 最近比较忙, 没有时间看, 问题找到原因了吗?
