### ISSUE TITLE
启动工程

### ISSUE THREAD

**Issue by Zhang-Yida** [jackhutu/jackblog-angular2#4]
gulp serve

前端的 angular2 项目中没有gulp的配置文件，这个命令执行不了啊。如果没有 express 后端的支持， 前端怎么运行起来啊

**Comment by hutuxuhui** [comment]
哈, 忘记改文档了, npm run dev
后端下载https://github.com/jackhutu/jackblog-api-express 或者 https://github.com/jackhutu/jackblog-api-koa
